### ISSUE TITLE
Building Information Page

### ISSUE THREAD

**Issue by jculilap** [khcanniff/TigAR#35]
This will handle:
- Scan sticker images
- Informational popups 
- Communicates with an online database for image recognition

Please check UI Design Draft for reference
**Please Check off what is done!**
- [ ]  [3] Informational instructions popup about using camera [here](https://github.com/khcanniff/TigAR/issues/40)
- [x]  [3]  Creation of sticker (different shapes) [here](https://github.com/khcanniff/TigAR/issues/41)
- [ ]  [5] UI Design [here](https://github.com/khcanniff/TigAR/issues/42)
- [ ]  [2] Exit button to main menu [here](https://github.com/khcanniff/TigAR/issues/43)
