### ISSUE TITLE
Locate Building Page

### ISSUE THREAD

**Issue by jculilap** [khcanniff/TigAR#36]
This will handle:
- Location tracking UI
- GPS augmented reality functionality
- Search capabilities for buildings
- 2D map viewer

Please refer to UI Design Draft for reference

---------------------------------------------
[13] Creation of form
- [ ] [3] section which lists buildings in alphabetical order with each building name being clickable. Once a building is selected the text color changes ( make sure only on building can be selected at a time). [Link](https://github.com/khcanniff/TigAR/issues/50)
- [ ] [2] creation of two buttons which appear only when a building is selected. first button is "Undo"  which unselects your choice and hides the two buttons. Second button is "Confirm?" which tirggers a boolean variable. [Link](https://github.com/khcanniff/TigAR/issues/51)
- [ ] [1] Adding a static image (map) [Link](https://github.com/khcanniff/TigAR/issues/52)
- [ ] [2] assigning coordinates for each building name [Link](https://github.com/khcanniff/TigAR/issues/53)
- [ ] [3] Creation of a data structure to hold the building name and coordinates [Link](https://github.com/khcanniff/TigAR/issues/54)
- [ ] [2] placing a circle for the relative/respective coordinates [Link](https://github.com/khcanniff/TigAR/issues/55)

---------------------------------------------
[19] GPS Overlay through camera
- [ ] [8] Graphical overlay arrows on the pathway based on the direction of the phone [Link](https://github.com/khcanniff/TigAR/issues/56)
- [ ] [8] Research implementation of  Google API (take notes), and implement a prototype in Unity [Link](https://github.com/khcanniff/TigAR/issues/57)
- [ ] [1] Exit button to take the user back to the main menu [Link](https://github.com/khcanniff/TigAR/issues/58)
- [ ] [2] Detection of arrival and arrival notification [Link](https://github.com/khcanniff/TigAR/issues/59)
