### ISSUE TITLE
Main Menu Page

### ISSUE THREAD

**Issue by jculilap** [khcanniff/TigAR#39]
It will house the buttons that can get to the other pages.

Reference the UI Draft design for more details.

**Can be creative as you want!**

- [x] [2] Working button for "Building Info"
- [x] [2] Working button for "Locate Building"
- [x] [2] Working button for "View Map"
- [x] [2] Working button for "About"
